### ISSUE TITLE
Improve wording

### ISSUE THREAD

**Issue by PierreBresson** [NMF-earth/carbon-footprint#14]
Simply rename `FoodEnum`, `TransportEnum`... to `FoodType`, `TransportType`...

_NB : due to spam, I won't assigned this task to anyone without previous contribution to this repo but PR are accepted, just have a look if there is no PR up and if this issue is not assigned to anyone_

**Comment by sathyasub** [comment]
@PierreBresson can you assign this to me

**Comment by PierreBresson** [comment]
https://github.com/NMF-earth/carbon-footprint/pull/15
