### ISSUE TITLE
Car purchase carbon impact

### ISSUE THREAD

**Issue by PierreBresson** [NMF-earth/carbon-footprint#19]
Add to [purchase file](https://github.com/NMF-earth/carbon-footprint/blob/master/src/purchase/purchase.ts) the impact of purchasing a fossil fuel and a electric car (type sedan, like bmw 3 serie / tesla s).

To do list : 

- [x] find the amount of kg CO2 of a fossil fuel car + electric car thanks to a reliable source of data on the internet. 
- [x] add it the `purchase.ts` (put the source url) and update `purchase.enum.ts`

**Comment by marlonemmerich** [comment]
Hey! Can I help with this?

**Comment by marlonemmerich** [comment]
Can you check please? This [PR](https://github.com/NMF-earth/carbon-footprint/pull/20)
Thanks!

**Comment by PierreBresson** [comment]
https://github.com/NMF-earth/carbon-footprint/pull/20
