### ISSUE TITLE
Can I have the authority to make dart package similar to this npm carbon-footprint package 

### ISSUE THREAD

**Issue by anaskhan28** [NMF-earth/carbon-footprint#29]

**Comment by anaskhan28** [comment]
I built one project in the Flutter application but to handle the stuff I was using API for carbon calculation but it doesn't make sense to call API every time user want to add their tracking data. So I thought of building a dart package similar to this carbon-footprint package

**Comment by PierreBresson** [comment]
Of course, that's good idea 👍
