### ISSUE TITLE
Consider adding a CONTRIBUTING.md file

### ISSUE THREAD

**Issue by MattMarquise** [NMF-earth/carbon-footprint#7]
Simply adding a CONTRIBUTING.md file will help show this is an open source project and you want help, as is briefly stated in the main README.

**Comment by PierreBresson** [comment]
Indeed, something like https://github.com/NMF-earth/nmf-app/blob/master/contributing.md would be nice

**Comment by syauqy** [comment]
Hi @MattMarquise and @PierreBresson , do you mean like this? #8

**Comment by Mishrasubha** [comment]
Can I take this?

**Comment by PierreBresson** [comment]
https://github.com/NMF-earth/carbon-footprint/pull/8

**Comment by MattMarquise** [comment]
@syauqy  > Hi @MattMarquise and @PierreBresson , do you mean like this? #8

yes!
